apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: my-app
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "my-nginx-app/secrets"
        objectType: "secretsmanager"
  secretObjects:
  - secretName: mysecret
    type: Opaque
    data:
    - objectName: my-nginx-app/secrets
      key: username
    - objectName: my-nginx-app/secrets
      key: password
