apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 3
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        albIngress: true

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: my-app-sa
      namespace: my-app
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
    - "arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess"